spring:
  application:
    name: pointroulette

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost:5433/pointroulette}
    username: ${POSTGRESQL_USERNAME:pointroulette}
    password: ${POSTGRESQL_PASSWORD:pointroulette}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

swagger:
  server:
    local:
      url: http://localhost:8080
#    production:
#      url: ${SWAGGER_PRODUCTION_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
